spring.application.name=Employee-Api

spring.profiles.active=prod

# N+1 문제를 보완해주는 설정
spring.jpa.properties.hibernate.default_batch_fetch_size=100

# schema file 경로 설정
spring.flyway.location=classpath:/db/migration/{vendor}
# 기존 DB가 있어도 Flyway가 인식하고 버전 관리 시작
spring.flyway.baselineOnMigrate=true
# flyway로 형상 관리 (애플리케이션 시작시 DB 버전 체크)
spring.flyway.enabled=true